version: '3'

vars:
  PROJECT_NAME: deeploop

tasks:
  install:
    desc: Install project dependencies
    cmds:
      - npm install

  dev:
    desc: Start development server
    cmds:
      - npm run dev

  build:
    desc: Build for production
    cmds:
      - npm run build

  test:
    desc: Run all tests
    cmds:
      - npm test

  test:watch:
    desc: Run tests in watch mode
    cmds:
      - npm run test:watch

  test:save:
    desc: Run only auto-save tests
    cmds:
      - npm run test:save

  lint:
    desc: Lint code with ESLint
    cmds:
      - npm run lint

  lint:fix:
    desc: Fix ESLint issues automatically
    cmds:
      - npm run lint:fix

  format:
    desc: Format code with Prettier
    cmds:
      - npm run format

  preview:
    desc: Preview production build locally
    cmds:
      - npm run preview

  clean:
    desc: Clean build artifacts and node_modules
    cmds:
      - rm -rf dist node_modules

  setup:
    desc: Full project setup - install dependencies and verify everything works
    cmds:
      - task: clean
      - task: install
      - task: test

  ci:
    desc: Run continuous integration checks
    cmds:
      - task: lint
      - task: test
      - task: build

  default:
    desc: Show available tasks
    cmds:
      - task --list